use crate::{asm::*, global::GlobalObjs, jvm::*, mapping_base::*, objs, util::UtilExt};
use alloc::{sync::Arc, vec::Vec};
use bstr::B;
use mapping_macros::Functor;

#[derive(Functor)]
pub struct ForgeCN<T> {
    pub fml: T,
    pub fml_ctx: T,
    pub evt_bus: T,
    pub reg_keys: T,
    pub reg_evt: T,
    pub block_cap: T,
    pub container_factory: T,
    pub forge_menu_type: T,
    pub player_ext: T,
    pub chunk_watch_base: T,
    pub chunk_watch_evt: T,
    pub chunk_unwatch_evt: T,
    pub chunk_load_evt: T,
    pub chunk_unload_evt: T,
    pub tile_ext: T,
    pub level_ext: T,
    pub reg_caps_evt: T,
    pub cap_provider: T,
    pub parallel_dispatch_evt: T,
    pub reg_payload_evt: T,
    pub payload_reg: T,
    pub payload_handler: T,
    pub payload_ctx: T,
    pub pkt_distributor: T,
    // Client
    pub render_lvl_stg_evt: T,
    pub render_lvl_stg: T,
    pub fml_client_setup_evt: T,
    pub renderers_evt: T,
    pub atlas_evt: T,
}

impl ForgeCN<Arc<CSig>> {
    pub fn new() -> Self {
        let names = ForgeCN::<&[u8]> {
            fml: b"net.neoforged.fml.loading.FMLLoader",
            fml_ctx: b"net.neoforged.fml.ModLoadingContext",
            evt_bus: b"net.neoforged.bus.api.IEventBus",
            reg_keys: b"net.neoforged.neoforge.registries.NeoForgeRegistries$Keys",
            reg_evt: b"net.neoforged.neoforge.registries.RegisterEvent",
            block_cap: b"net.neoforged.neoforge.capabilities.BlockCapability",
            container_factory: b"net.neoforged.neoforge.network.IContainerFactory",
            forge_menu_type: b"net.neoforged.neoforge.common.extensions.IMenuTypeExtension",
            player_ext: b"net.neoforged.neoforge.common.extensions.IPlayerExtension",
            chunk_watch_base: b"net.neoforged.neoforge.event.level.ChunkWatchEvent",
            chunk_watch_evt: b"net.neoforged.neoforge.event.level.ChunkWatchEvent$Watch",
            chunk_unwatch_evt: b"net.neoforged.neoforge.event.level.ChunkWatchEvent$UnWatch",
            chunk_load_evt: b"net.neoforged.neoforge.event.level.ChunkEvent$Load",
            chunk_unload_evt: b"net.neoforged.neoforge.event.level.ChunkEvent$Unload",
            tile_ext: b"net.neoforged.neoforge.common.extensions.IBlockEntityExtension",
            level_ext: b"net.neoforged.neoforge.common.extensions.ILevelExtension",
            reg_caps_evt: b"net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent",
            cap_provider: b"net.neoforged.neoforge.capabilities.ICapabilityProvider",
            parallel_dispatch_evt: b"net.neoforged.fml.event.lifecycle.ParallelDispatchEvent",
            reg_payload_evt: b"net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent",
            payload_reg: b"net.neoforged.neoforge.network.registration.PayloadRegistrar",
            payload_handler: b"net.neoforged.neoforge.network.handling.IPayloadHandler",
            payload_ctx: b"net.neoforged.neoforge.network.handling.IPayloadContext",
            pkt_distributor: b"net.neoforged.neoforge.network.PacketDistributor",
            // Client
            render_lvl_stg_evt: b"net.neoforged.neoforge.client.event.RenderLevelStageEvent",
            render_lvl_stg: b"net.neoforged.neoforge.client.event.RenderLevelStageEvent$Stage",
            fml_client_setup_evt: b"net.neoforged.fml.event.lifecycle.FMLClientSetupEvent",
            renderers_evt: b"net.neoforged.neoforge.client.event.EntityRenderersEvent$RegisterRenderers",
            atlas_evt: b"net.neoforged.neoforge.client.event.TextureAtlasStitchedEvent",
        };
        names.fmap(|x| Arc::new(CSig::new(x)))
    }
}

pub struct ForgeMN {
    pub container_factory_create: MSig,
    pub forge_menu_type_create: MSig,
    pub player_open_menu: MSig,
    pub enqueue_work: MSig,
    pub level_get_cap: MSig,
    pub cap_provider_get_cap: MSig,
    pub reg_caps_evt_reg_tile: MSig,
    pub reg_payload_evt_reg: MSig,
    pub payload_reg_bidir: MSig,
    pub handle_payload: MSig,
    pub send_c2s: MSig,
    pub send_s2c: MSig,
}

impl ForgeMN {
    pub fn new(cn: &CN<Arc<CSig>>, fcn: &ForgeCN<Arc<CSig>>) -> Self {
        Self {
            container_factory_create: MSig {
                owner: fcn.container_factory.clone(),
                name: cs("create"),
                sig: msig([b"I", cn.inventory.sig.to_bytes(), cn.reg_friendly_byte_buf.sig.to_bytes()], cn.container_menu.sig.to_bytes()),
            },
            forge_menu_type_create: MSig {
                owner: fcn.forge_menu_type.clone(),
                name: cs("create"),
                sig: msig([fcn.container_factory.sig.to_bytes()], cn.menu_type.sig.to_bytes()),
            },
            player_open_menu: MSig {
                owner: fcn.player_ext.clone(),
                name: cs("openMenu"),
                sig: msig([cn.menu_provider.sig.to_bytes(), b"Ljava/util/function/Consumer;"], b"Ljava/util/OptionalInt;"),
            },
            enqueue_work: MSig {
                owner: fcn.parallel_dispatch_evt.clone(),
                name: cs("enqueueWork"),
                sig: cs("(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;"),
            },
            level_get_cap: MSig {
                owner: fcn.level_ext.clone(),
                name: cs("getCapability"),
                sig: msig([fcn.block_cap.sig.to_bytes(), cn.block_pos.sig.to_bytes(), b"Ljava/lang/Object;"], b"Ljava/lang/Object;"),
            },
            cap_provider_get_cap: MSig {
                owner: fcn.cap_provider.clone(),
                name: cs("getCapability"),
                sig: cs("(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"),
            },
            reg_caps_evt_reg_tile: MSig {
                owner: fcn.reg_caps_evt.clone(),
                name: cs("registerBlockEntity"),
                sig: msig([fcn.block_cap.sig.to_bytes(), cn.tile_type.sig.to_bytes(), fcn.cap_provider.sig.to_bytes()], b"V"),
            },
            reg_payload_evt_reg: MSig {
                owner: fcn.reg_payload_evt.clone(),
                name: cs("registrar"),
                sig: msig([B("Ljava/lang/String;")], fcn.payload_reg.sig.to_bytes()),
            },
            payload_reg_bidir: MSig {
                owner: fcn.payload_reg.clone(),
                name: cs("playBidirectional"),
                sig: msig(
                    [cn.custom_payload_type.sig.to_bytes(), cn.stream_codec.sig.to_bytes(), fcn.payload_handler.sig.to_bytes()],
                    fcn.payload_reg.sig.to_bytes(),
                ),
            },
            handle_payload: MSig {
                owner: fcn.payload_handler.clone(),
                name: cs("handle"),
                sig: msig([cn.custom_payload.sig.to_bytes(), fcn.payload_ctx.sig.to_bytes()], b"V"),
            },
            send_c2s: MSig {
                owner: fcn.pkt_distributor.clone(),
                name: cs("sendToServer"),
                sig: msig([cn.custom_payload.sig.to_bytes(), b"[", cn.custom_payload.sig.to_bytes()], b"V"),
            },
            send_s2c: MSig {
                owner: fcn.pkt_distributor.clone(),
                name: cs("sendToPlayer"),
                sig: msig([cn.server_player.sig.to_bytes(), cn.custom_payload.sig.to_bytes(), b"[", cn.custom_payload.sig.to_bytes()], b"V"),
            },
        }
    }
}

pub struct ForgeMV {
    pub mod_evt_bus: GlobalRef<'static>,
    pub com_evt_bus: GlobalRef<'static>,
    pub evt_bus_add_listener: usize,
    pub reg_evt_key: usize,
    pub reg_evt_get_reg: usize,
    pub forge_menu_type: GlobalRef<'static>,
    pub forge_menu_type_create: usize,
    pub player_open_menu: usize,
    pub parallel_dispatch_evt_enqueue: usize,
    pub chunk_watch_player: usize,
    pub chunk_watch_pos: usize,
    pub chunk_watch_level: usize,
    pub level_evt_level: usize,
    pub chunk_evt_chunk: usize,
    pub level_get_cap: usize,
    pub reg_caps_evt_reg_tile: usize,
    pub reg_payload_evt_reg: usize,
    pub payload_reg_bidir: usize,
    pub payload_ctx_flow: usize,
    pub payload_ctx_player: usize,
    pub pkt_flow_is_s2c: usize,
    pub pkt_distributor: GlobalRef<'static>,
    pub send_c2s: usize,
    pub send_s2c: usize,
    pub client: Option<ForgeMVC>,
}

pub struct ForgeMVC {
    pub renderers_evt_reg: usize,
    pub atlas_evt_get_atlas: usize,
    pub render_lvl_stg_after_tiles: GlobalRef<'static>,
    pub render_lvl_stg_evt_stage: usize,
    pub render_lvl_stg_evt_renderer: usize,
    pub render_lvl_stg_evt_pose: usize,
    pub render_lvl_stg_evt_camera: usize,
    pub render_lvl_stg_evt_tick: usize,
    pub render_lvl_stg_evt_sub_tick: usize,
}

impl ForgeMV {
    pub fn new(av: &AV<'static>, cn: &CN<Arc<CSig>>, fcn: &ForgeCN<Arc<CSig>>, fmn: &ForgeMN) -> Self {
        let load = |csig: &Arc<CSig>| av.ldr.load_class(&av.jv, &csig.dot).unwrap().new_global_ref().unwrap();
        let fml = av.ldr.load_class(&av.jv, c"net.neoforged.fml.loading.FMLLoader").unwrap();
        let fml_ctx = load(&fcn.fml_ctx);
        let fml_ctx_inst = fml_ctx.get_static_method_id(c"get", &msig([], fcn.fml_ctx.sig.to_bytes())).unwrap();
        let fml_ctx_inst = fml_ctx.call_static_object_method(fml_ctx_inst, &[]).unwrap().unwrap();
        let container_inst = fml_ctx.get_method_id(c"getActiveContainer", c"()Lnet/neoforged/fml/ModContainer;").unwrap();
        let container_inst = fml_ctx_inst.call_object_method(container_inst, &[]).unwrap().unwrap();
        let container = container_inst.get_object_class();
        let evt_bus = load(&fcn.evt_bus);
        let mod_evt_bus = container.get_method_id(c"getEventBus", &msig([], fcn.evt_bus.sig.to_bytes())).unwrap();
        let mod_evt_bus = container_inst.call_object_method(mod_evt_bus, &[]).unwrap().unwrap().new_global_ref().unwrap();
        let forge = av.ldr.load_class(&av.jv, c"net.neoforged.neoforge.common.NeoForge").unwrap();
        let reg_evt = load(&fcn.reg_evt);
        let forge_menu_type = load(&fcn.forge_menu_type);
        let parallel_dispatch_evt = load(&fcn.parallel_dispatch_evt);
        let chunk_watch_base = load(&fcn.chunk_watch_base);
        let chunk_evt = av.ldr.load_class(&av.jv, c"net.neoforged.neoforge.event.level.ChunkEvent").unwrap();
        let level_evt = av.ldr.load_class(&av.jv, c"net.neoforged.neoforge.event.level.LevelEvent").unwrap();
        let payload_ctx = load(&fcn.payload_ctx);
        let pkt_flow_ext = av.ldr.load_class(&av.jv, c"net.neoforged.neoforge.common.extensions.IPacketFlowExtension").unwrap();
        let pkt_distributor = load(&fcn.pkt_distributor);
        let dist = fml.static_field_1(c"dist", c"Lnet/neoforged/api/distmarker/Dist;");
        let is_client = dist.call_bool_method(dist.get_object_class().get_method_id(c"isClient", c"()Z").unwrap(), &[]).unwrap();
        Self {
            mod_evt_bus,
            com_evt_bus: forge.static_field_1(c"EVENT_BUS", &fcn.evt_bus.sig),
            evt_bus_add_listener: evt_bus.get_method_id(c"addListener", c"(Ljava/util/function/Consumer;)V").unwrap(),
            reg_evt_key: reg_evt.get_method_id(c"getRegistryKey", &msig([], cn.resource_key.sig.to_bytes())).unwrap(),
            reg_evt_get_reg: reg_evt.get_method_id(c"getRegistry", &msig([], cn.registry.sig.to_bytes())).unwrap(),
            forge_menu_type_create: fmn.forge_menu_type_create.get_static_method_id(&forge_menu_type).unwrap(),
            forge_menu_type,
            player_open_menu: fmn.player_open_menu.get_method_id(&load(&fcn.player_ext)).unwrap(),
            parallel_dispatch_evt_enqueue: fmn.enqueue_work.get_method_id(&parallel_dispatch_evt).unwrap(),
            chunk_watch_level: chunk_watch_base.get_field_id(c"level", &cn.server_level.sig).unwrap(),
            chunk_watch_player: chunk_watch_base.get_field_id(c"player", &cn.server_player.sig).unwrap(),
            chunk_watch_pos: chunk_watch_base.get_field_id(c"pos", &cn.chunk_pos.sig).unwrap(),
            chunk_evt_chunk: chunk_evt.get_field_id(c"chunk", &cn.chunk_access.sig).unwrap(),
            level_evt_level: level_evt.get_field_id(c"level", &cn.level_access.sig).unwrap(),
            level_get_cap: fmn.level_get_cap.get_method_id(&load(&fcn.level_ext)).unwrap(),
            reg_caps_evt_reg_tile: fmn.reg_caps_evt_reg_tile.get_method_id(&load(&fcn.reg_caps_evt)).unwrap(),
            reg_payload_evt_reg: fmn.reg_payload_evt_reg.get_method_id(&load(&fcn.reg_payload_evt)).unwrap(),
            payload_reg_bidir: fmn.payload_reg_bidir.get_method_id(&load(&fcn.payload_reg)).unwrap(),
            payload_ctx_flow: payload_ctx.get_method_id(c"flow", &msig([], cn.pkt_flow.sig.to_bytes())).unwrap(),
            payload_ctx_player: payload_ctx.get_method_id(c"player", &msig([], &cn.player.sig.to_bytes())).unwrap(),
            pkt_flow_is_s2c: pkt_flow_ext.get_method_id(c"isClientbound", c"()Z").unwrap(),
            send_c2s: fmn.send_c2s.get_static_method_id(&pkt_distributor).unwrap(),
            send_s2c: fmn.send_s2c.get_static_method_id(&pkt_distributor).unwrap(),
            pkt_distributor,
            client: is_client.then(|| {
                let renderers_evt = load(&fcn.renderers_evt);
                let renderers_evt_reg = msig([cn.tile_type.sig.to_bytes(), cn.tile_renderer_provider.sig.to_bytes()], b"V");
                let atlas_evt = load(&fcn.atlas_evt);
                ForgeMVC {
                    renderers_evt_reg: renderers_evt.get_method_id(c"registerBlockEntityRenderer", &renderers_evt_reg).unwrap(),
                    atlas_evt_get_atlas: atlas_evt.get_method_id(c"getAtlas", &msig([], cn.atlas.sig.to_bytes())).unwrap(),
                    render_lvl_stg_after_tiles: load(&fcn.render_lvl_stg).static_field_1(c"AFTER_BLOCK_ENTITIES", &fcn.render_lvl_stg.sig),
                    render_lvl_stg_evt_stage: load(&fcn.render_lvl_stg_evt).get_field_id(c"stage", &fcn.render_lvl_stg.sig).unwrap(),
                    render_lvl_stg_evt_renderer: load(&fcn.render_lvl_stg_evt).get_field_id(c"levelRenderer", &cn.level_renderer.sig).unwrap(),
                    render_lvl_stg_evt_pose: load(&fcn.render_lvl_stg_evt).get_field_id(c"poseStack", &cn.pose_stack.sig).unwrap(),
                    render_lvl_stg_evt_camera: load(&fcn.render_lvl_stg_evt).get_field_id(c"camera", &cn.camera.sig).unwrap(),
                    render_lvl_stg_evt_tick: load(&fcn.render_lvl_stg_evt).get_field_id(c"renderTick", c"I").unwrap(),
                    render_lvl_stg_evt_sub_tick: load(&fcn.render_lvl_stg_evt).get_field_id(c"partialTick", &cn.delta_tracker.sig).unwrap(),
                }
            }),
        }
    }
}

#[derive(Functor)]
pub struct CN<T> {
    pub block: T,
    pub block_beh: T,
    pub block_beh_props: T,
    pub block_getter: T,
    pub blocks: T,
    pub level: T,
    pub base_tile_block: T,
    pub tile_block: T,
    pub resource_key: T,
    pub item: T,
    pub item_props: T,
    pub item_stack: T,
    pub item_like: T,
    pub block_item: T,
    pub tile: T,
    pub tile_supplier: T,
    pub tile_type: T,
    pub vec3i: T,
    pub vec3d: T,
    pub block_pos: T,
    pub block_state: T,
    pub dfu_type: T,
    pub sound_type: T,
    pub creative_tab_items_gen: T,
    pub creative_tab_params: T,
    pub creative_tab_output: T,
    pub render_shape: T,
    pub resource_loc: T,
    pub voxel_shape: T,
    pub shapes: T,
    pub collision_ctx: T,
    pub block_place_ctx: T,
    pub use_on_ctx: T,
    pub interaction_result: T,
    pub s2c_tile_data: T,
    pub nbt_compound: T,
    pub pkt: T,
    pub living_entity: T,
    pub dir: T,
    pub loot_builder: T,
    pub container_menu: T,
    pub inventory: T,
    pub friendly_byte_buf: T,
    pub reg_friendly_byte_buf: T,
    pub menu_type: T,
    pub server_player: T,
    pub menu_provider: T,
    pub player: T,
    pub chat_component: T,
    pub chat_mutable_component: T,
    pub chat_fmt: T,
    pub formatted_char_seq: T,
    pub block_hit_result: T,
    pub entity: T,
    pub container: T,
    pub game_profile: T,
    pub holder: T,
    pub holder_ref: T,
    pub holder_provider: T,
    pub sound_evts: T,
    pub chunk_source: T,
    pub server_chunk_cache: T,
    pub tile_ticker: T,
    pub server_level: T,
    pub chunk_pos: T,
    pub chunk_access: T,
    pub level_access: T,
    pub level_chunk: T,
    pub registry: T,
    pub registries: T,
    pub stream_codec: T,
    pub custom_payload: T,
    pub custom_payload_type: T,
    pub pkt_flow: T,
    // Client
    pub tile_renderer: T,
    pub tile_renderer_provider: T,
    pub tile_renderer_provider_ctx: T,
    pub pose_stack: T,
    pub pose: T,
    pub matrix4f: T,
    pub matrix4fc: T,
    pub atlas: T,
    pub sprite: T,
    pub sheets: T,
    pub multi_buffer_source: T,
    pub buffer_source: T,
    pub vertex_consumer: T,
    pub render_type: T,
    pub menu_screens: T,
    pub screen_constructor: T,
    pub container_screen: T,
    pub screen: T,
    pub gui_graphics: T,
    pub font: T,
    pub game_renderer: T,
    pub render_sys: T,
    pub shader_inst: T,
    pub tesselator: T,
    pub vertex_mode: T,
    pub vertex_fmt: T,
    pub default_vertex_fmt: T,
    pub buffer_builder: T,
    pub mc: T,
    pub window: T,
    pub sound_mgr: T,
    pub sound_inst: T,
    pub simple_sound_inst: T,
    pub level_renderer: T,
    pub render_buffers: T,
    pub camera: T,
    pub local_player: T,
    pub buffer_uploader: T,
    pub mesh_data: T,
    pub delta_tracker: T,
}

impl CN<Arc<CSig>> {
    pub fn new() -> Self {
        let names = CN::<&[u8]> {
            block: b"net.minecraft.world.level.block.Block",
            block_beh: b"net.minecraft.world.level.block.state.BlockBehaviour",
            block_beh_props: b"net.minecraft.world.level.block.state.BlockBehaviour$Properties",
            block_getter: b"net.minecraft.world.level.BlockGetter",
            blocks: b"net.minecraft.world.level.block.Blocks",
            level: b"net.minecraft.world.level.Level",
            base_tile_block: b"net.minecraft.world.level.block.BaseEntityBlock",
            tile_block: b"net.minecraft.world.level.block.EntityBlock",
            resource_key: b"net.minecraft.resources.ResourceKey",
            item: b"net.minecraft.world.item.Item",
            item_props: b"net.minecraft.world.item.Item$Properties",
            item_stack: b"net.minecraft.world.item.ItemStack",
            item_like: b"net.minecraft.world.level.ItemLike",
            block_item: b"net.minecraft.world.item.BlockItem",
            tile: b"net.minecraft.world.level.block.entity.BlockEntity",
            tile_supplier: b"net.minecraft.world.level.block.entity.BlockEntityType$BlockEntitySupplier",
            tile_type: b"net.minecraft.world.level.block.entity.BlockEntityType",
            vec3i: b"net.minecraft.core.Vec3i",
            vec3d: b"net.minecraft.world.phys.Vec3",
            block_pos: b"net.minecraft.core.BlockPos",
            block_state: b"net.minecraft.world.level.block.state.BlockState",
            dfu_type: b"com.mojang.datafixers.types.Type",
            sound_type: b"net.minecraft.world.level.block.SoundType",
            voxel_shape: b"net.minecraft.world.phys.shapes.VoxelShape",
            shapes: b"net.minecraft.world.phys.shapes.Shapes",
            creative_tab_items_gen: b"net.minecraft.world.item.CreativeModeTab$DisplayItemsGenerator",
            creative_tab_params: b"net.minecraft.world.item.CreativeModeTab$ItemDisplayParameters",
            creative_tab_output: b"net.minecraft.world.item.CreativeModeTab$Output",
            render_shape: b"net.minecraft.world.level.block.RenderShape",
            resource_loc: b"net.minecraft.resources.ResourceLocation",
            collision_ctx: b"net.minecraft.world.phys.shapes.CollisionContext",
            block_place_ctx: b"net.minecraft.world.item.context.BlockPlaceContext",
            use_on_ctx: b"net.minecraft.world.item.context.UseOnContext",
            interaction_result: b"net.minecraft.world.InteractionResult",
            s2c_tile_data: b"net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket",
            nbt_compound: b"net.minecraft.nbt.CompoundTag",
            pkt: b"net.minecraft.network.protocol.Packet",
            living_entity: b"net.minecraft.world.entity.LivingEntity",
            dir: b"net.minecraft.core.Direction",
            loot_builder: b"net.minecraft.world.level.storage.loot.LootParams$Builder",
            container_menu: b"net.minecraft.world.inventory.AbstractContainerMenu",
            inventory: b"net.minecraft.world.entity.player.Inventory",
            friendly_byte_buf: b"net.minecraft.network.FriendlyByteBuf",
            reg_friendly_byte_buf: b"net.minecraft.network.RegistryFriendlyByteBuf",
            menu_type: b"net.minecraft.world.inventory.MenuType",
            server_player: b"net.minecraft.server.level.ServerPlayer",
            menu_provider: b"net.minecraft.world.MenuProvider",
            player: b"net.minecraft.world.entity.player.Player",
            chat_component: b"net.minecraft.network.chat.Component",
            chat_mutable_component: b"net.minecraft.network.chat.MutableComponent",
            chat_fmt: b"net.minecraft.ChatFormatting",
            formatted_char_seq: b"net.minecraft.util.FormattedCharSequence",
            block_hit_result: b"net.minecraft.world.phys.BlockHitResult",
            entity: b"net.minecraft.world.entity.Entity",
            container: b"net.minecraft.world.Container",
            game_profile: b"com.mojang.authlib.GameProfile",
            holder: b"net.minecraft.core.Holder",
            holder_ref: b"net.minecraft.core.Holder$Reference",
            holder_provider: b"net.minecraft.core.HolderLookup$Provider",
            sound_evts: b"net.minecraft.sounds.SoundEvents",
            chunk_source: b"net.minecraft.world.level.chunk.ChunkSource",
            server_chunk_cache: b"net.minecraft.server.level.ServerChunkCache",
            tile_ticker: b"net.minecraft.world.level.block.entity.BlockEntityTicker",
            server_level: b"net.minecraft.server.level.ServerLevel",
            chunk_pos: b"net.minecraft.world.level.ChunkPos",
            chunk_access: b"net.minecraft.world.level.chunk.ChunkAccess",
            level_access: b"net.minecraft.world.level.LevelAccessor",
            level_chunk: b"net.minecraft.world.level.chunk.LevelChunk",
            registry: b"net.minecraft.core.Registry",
            registries: b"net.minecraft.core.registries.Registries",
            stream_codec: b"net.minecraft.network.codec.StreamCodec",
            custom_payload: b"net.minecraft.network.protocol.common.custom.CustomPacketPayload",
            custom_payload_type: b"net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type",
            pkt_flow: b"net.minecraft.network.protocol.PacketFlow",
            // Client
            tile_renderer: b"net.minecraft.client.renderer.blockentity.BlockEntityRenderer",
            tile_renderer_provider: b"net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider",
            tile_renderer_provider_ctx: b"net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider$Context",
            pose_stack: b"com.mojang.blaze3d.vertex.PoseStack",
            pose: b"com.mojang.blaze3d.vertex.PoseStack$Pose",
            matrix4f: b"org.joml.Matrix4f",
            matrix4fc: b"org.joml.Matrix4fc",
            atlas: b"net.minecraft.client.renderer.texture.TextureAtlas",
            sprite: b"net.minecraft.client.renderer.texture.TextureAtlasSprite",
            sheets: b"net.minecraft.client.renderer.Sheets",
            multi_buffer_source: b"net.minecraft.client.renderer.MultiBufferSource",
            buffer_source: b"net.minecraft.client.renderer.MultiBufferSource$BufferSource",
            vertex_consumer: b"com.mojang.blaze3d.vertex.VertexConsumer",
            render_type: b"net.minecraft.client.renderer.RenderType",
            menu_screens: b"net.minecraft.client.gui.screens.MenuScreens",
            screen_constructor: b"net.minecraft.client.gui.screens.MenuScreens$ScreenConstructor",
            container_screen: b"net.minecraft.client.gui.screens.inventory.AbstractContainerScreen",
            screen: b"net.minecraft.client.gui.screens.Screen",
            gui_graphics: b"net.minecraft.client.gui.GuiGraphics",
            font: b"net.minecraft.client.gui.Font",
            game_renderer: b"net.minecraft.client.renderer.GameRenderer",
            render_sys: b"com.mojang.blaze3d.systems.RenderSystem",
            shader_inst: b"net.minecraft.client.renderer.ShaderInstance",
            tesselator: b"com.mojang.blaze3d.vertex.Tesselator",
            vertex_mode: b"com.mojang.blaze3d.vertex.VertexFormat$Mode",
            vertex_fmt: b"com.mojang.blaze3d.vertex.VertexFormat",
            default_vertex_fmt: b"com.mojang.blaze3d.vertex.DefaultVertexFormat",
            buffer_builder: b"com.mojang.blaze3d.vertex.BufferBuilder",
            mc: b"net.minecraft.client.Minecraft",
            window: b"com.mojang.blaze3d.platform.Window",
            sound_mgr: b"net.minecraft.client.sounds.SoundManager",
            sound_inst: b"net.minecraft.client.resources.sounds.SoundInstance",
            simple_sound_inst: b"net.minecraft.client.resources.sounds.SimpleSoundInstance",
            level_renderer: b"net.minecraft.client.renderer.LevelRenderer",
            render_buffers: b"net.minecraft.client.renderer.RenderBuffers",
            camera: b"net.minecraft.client.Camera",
            local_player: b"net.minecraft.client.player.LocalPlayer",
            buffer_uploader: b"com.mojang.blaze3d.vertex.BufferUploader",
            mesh_data: b"com.mojang.blaze3d.vertex.MeshData",
            delta_tracker: b"net.minecraft.client.DeltaTracker",
        };
        names.fmap(|x| Arc::new(CSig::new(x)))
    }
}

#[derive(Functor)]
pub struct MN<T> {
    pub base_tile_block_init: T,
    pub tile_block_new_tile: T,
    pub tile_block_get_ticker: T,
    pub block_default_state: T,
    pub block_beh_props_of: T,
    pub block_beh_props_strength: T,
    pub block_beh_props_dyn_shape: T,
    pub block_beh_props_sound: T,
    pub block_beh_get_render_shape: T,
    pub block_beh_get_shape: T,
    pub block_beh_get_drops: T,
    pub block_beh_on_place: T,
    pub block_beh_use: T,
    pub block_item_init: T,
    pub block_item_place_block: T,
    pub block_getter_get_block_state: T,
    pub block_getter_get_tile: T,
    pub vec3i_x: T,
    pub vec3i_y: T,
    pub vec3i_z: T,
    pub vec3d_init: T,
    pub vec3d_x: T,
    pub vec3d_y: T,
    pub vec3d_z: T,
    pub block_pos_init: T,
    pub block_state_get_block: T,
    pub block_state_get_visual_shape: T,
    pub blocks_fire: T,
    pub tile_supplier_create: T,
    pub tile_type_init: T,
    pub tile_init: T,
    pub tile_load_additional: T,
    pub tile_get_update_tag: T,
    pub tile_get_update_pkt: T,
    pub tile_save_additional: T,
    pub tile_level: T,
    pub tile_pos: T,
    pub tile_set_removed: T,
    pub tile_set_changed: T,
    pub sound_type_metal: T,
    pub item_get_desc_id: T,
    pub item_stack_init: T,
    pub creative_tab_items_gen_accept: T,
    pub render_shape_tile: T,
    pub resource_loc_init: T,
    pub shapes_create: T,
    pub collision_ctx_empty: T,
    pub s2c_tile_data_create: T,
    pub nbt_compound_init: T,
    pub nbt_compound_put_byte_array: T,
    pub nbt_compound_get_byte_array: T,
    pub use_on_ctx_get_level: T,
    pub use_on_ctx_get_clicked_pos: T,
    pub use_on_ctx_get_clicked_face: T,
    pub dir_3d_data: T,
    pub dir_by_3d_data: T,
    pub level_set_block_and_update: T,
    pub level_update_neighbors_for_out_signal: T,
    pub level_is_client: T,
    pub level_get_chunk_source: T,
    pub level_is_outside_build_height: T,
    pub container_menu_init: T,
    pub container_menu_still_valid: T,
    pub container_menu_quick_move_stack: T,
    pub container_menu_id: T,
    pub menu_provider_create_menu: T,
    pub menu_provider_get_display_name: T,
    pub chat_component_translatable: T,
    pub chat_component_literal: T,
    pub chat_component_to_formatted: T,
    pub chat_fmt_from_code: T,
    pub chat_fmt_color: T,
    pub friendly_byte_buf_read_byte_array: T,
    pub friendly_byte_buf_write_byte_array: T,
    pub inventory_player: T,
    pub entity_level: T,
    pub entity_y_rot: T,
    pub container_still_valid: T,
    pub player_profile: T,
    pub player_container_menu: T,
    pub game_profile_get_name: T,
    pub sound_evts_ui_btn_click: T,
    pub server_chunk_cache_block_changed: T,
    pub tile_ticker_tick: T,
    pub chunk_pos_x: T,
    pub chunk_pos_z: T,
    pub voxel_shape_clip: T,
    pub block_hit_result_pos: T,
    pub block_hit_result_miss: T,
    pub block_hit_result_dir: T,
    pub chunk_access_pos: T,
    pub level_chunk_set_block_state: T,
    pub level_chunk_level: T,
    pub chunk_source_get_chunk_now: T,
    pub registry_reg: T,
    pub reg_key_block: T,
    pub reg_key_tile_type: T,
    pub reg_key_menu: T,
    pub custom_payload_type: T,
    pub custom_payload_type_init: T,
    pub stream_codec_encode: T,
    pub stream_codec_decode: T,
    // Client
    pub tile_renderer_render: T,
    pub tile_renderer_provider_create: T,
    pub pose_pose: T,
    pub pose_stack_last: T,
    pub matrix4fc_read: T,
    pub atlas_loc: T,
    pub atlas_loc_blocks: T,
    pub atlas_get_sprite: T,
    pub sprite_u0: T,
    pub sprite_v0: T,
    pub sprite_u1: T,
    pub sprite_v1: T,
    pub sheets_solid: T,
    pub multi_buffer_source_get_buffer: T,
    pub buffer_source_end_batch: T,
    pub vertex_consumer_vertex: T,
    pub vertex_consumer_pos: T,
    pub vertex_consumer_color: T,
    pub menu_screens_reg: T,
    pub screen_constructor_create: T,
    pub screen_title: T,
    pub screen_font: T,
    pub screen_width: T,
    pub screen_height: T,
    pub screen_render_background: T,
    pub container_screen_init: T,
    pub container_screen_minit: T,
    pub container_screen_img_width: T,
    pub container_screen_img_height: T,
    pub container_screen_title_x: T,
    pub container_screen_title_y: T,
    pub container_screen_left: T,
    pub container_screen_top: T,
    pub container_screen_menu: T,
    pub container_screen_render_bg: T,
    pub container_screen_render_labels: T,
    pub container_screen_mouse_clicked: T,
    pub container_screen_mouse_dragged: T,
    pub container_screen_mouse_released: T,
    pub gui_graphics_draw_formatted: T,
    pub gui_graphics_pose: T,
    pub render_sys_set_shader: T,
    pub render_sys_enable_blend: T,
    pub render_sys_enable_cull: T,
    pub render_sys_disable_blend: T,
    pub render_sys_disable_cull: T,
    pub game_renderer_get_pos_color_shader: T,
    pub tesselator_get_inst: T,
    pub tesselator_begin: T,
    pub vertex_mode_tris: T,
    pub default_vertex_fmt_pos_color: T,
    pub buffer_builder_build: T,
    pub mc_get_inst: T,
    pub mc_get_window: T,
    pub mc_get_sound_mgr: T,
    pub mc_clear_level: T,
    pub mc_player: T,
    pub window_get_gui_scale: T,
    pub font_width: T,
    pub sound_mgr_play: T,
    pub simple_sound_inst_for_ui_holder: T,
    pub render_type_lightning: T,
    pub level_renderer_buffers: T,
    pub render_buffers_buffer_source: T,
    pub camera_pos: T,
    pub buffer_uploader_draw: T,
    pub delta_tracker_get_partial_tick: T,
}

impl MN<MSig> {
    pub fn new(cn: &CN<Arc<CSig>>) -> Self {
        MN {
            base_tile_block_init: MSig {
                owner: cn.base_tile_block.clone(),
                name: cs("<init>"),
                sig: msig([cn.block_beh_props.sig.to_bytes()], b"V"),
            },
            tile_block_new_tile: MSig {
                owner: cn.tile_block.clone(),
                name: cs("newBlockEntity"),
                sig: msig([cn.block_pos.sig.to_bytes(), cn.block_state.sig.to_bytes()], cn.tile.sig.to_bytes()),
            },
            tile_block_get_ticker: MSig {
                owner: cn.tile_block.clone(),
                name: cs("getTicker"),
                sig: msig([cn.level.sig.to_bytes(), cn.block_state.sig.to_bytes(), cn.tile_type.sig.to_bytes()], cn.tile_ticker.sig.to_bytes()),
            },
            block_default_state: MSig { owner: cn.block.clone(), name: cs("defaultBlockState"), sig: msig([], cn.block_state.sig.to_bytes()) },
            block_beh_props_of: MSig { owner: cn.block_beh_props.clone(), name: cs("of"), sig: msig([], cn.block_beh_props.sig.to_bytes()) },
            block_beh_props_strength: MSig {
                owner: cn.block_beh_props.clone(),
                name: cs("strength"),
                sig: msig([B("FF")], cn.block_beh_props.sig.to_bytes()),
            },
            block_beh_props_dyn_shape: MSig {
                owner: cn.block_beh_props.clone(),
                name: cs("dynamicShape"),
                sig: msig([], cn.block_beh_props.sig.to_bytes()),
            },
            block_beh_props_sound: MSig {
                owner: cn.block_beh_props.clone(),
                name: cs("sound"),
                sig: msig([cn.sound_type.sig.to_bytes()], cn.block_beh_props.sig.to_bytes()),
            },
            block_beh_get_render_shape: MSig {
                owner: cn.block_beh.clone(),
                name: cs("getRenderShape"),
                sig: msig([cn.block_state.sig.to_bytes()], cn.render_shape.sig.to_bytes()),
            },
            block_beh_get_shape: MSig {
                owner: cn.block_beh.clone(),
                name: cs("getShape"),
                sig: msig(
                    [cn.block_state.sig.to_bytes(), cn.block_getter.sig.to_bytes(), cn.block_pos.sig.to_bytes(), cn.collision_ctx.sig.to_bytes()],
                    cn.voxel_shape.sig.to_bytes(),
                ),
            },
            block_beh_get_drops: MSig {
                owner: cn.block_beh.clone(),
                name: cs("getDrops"),
                sig: msig([cn.block_state.sig.to_bytes(), cn.loot_builder.sig.to_bytes()], b"Ljava/util/List;"),
            },
            block_beh_on_place: MSig {
                owner: cn.block_beh.clone(),
                name: cs("onPlace"),
                sig: msig(
                    [cn.block_state.sig.to_bytes(), cn.level.sig.to_bytes(), cn.block_pos.sig.to_bytes(), cn.block_state.sig.to_bytes(), b"Z"],
                    b"V",
                ),
            },
            block_beh_use: MSig {
                owner: cn.block_beh.clone(),
                name: cs(b"useWithoutItem"),
                sig: msig(
                    [
                        cn.block_state.sig.to_bytes(),
                        cn.level.sig.to_bytes(),
                        cn.block_pos.sig.to_bytes(),
                        cn.player.sig.to_bytes(),
                        cn.block_hit_result.sig.to_bytes(),
                    ],
                    cn.interaction_result.sig.to_bytes(),
                ),
            },
            block_item_init: MSig {
                owner: cn.block_item.clone(),
                name: cs("<init>"),
                sig: msig([cn.block.sig.to_bytes(), cn.item_props.sig.to_bytes()], b"V"),
            },
            block_item_place_block: MSig {
                owner: cn.block_item.clone(),
                name: cs("placeBlock"),
                sig: msig([cn.block_place_ctx.sig.to_bytes(), cn.block_state.sig.to_bytes()], b"Z"),
            },
            block_getter_get_block_state: MSig {
                owner: cn.block_getter.clone(),
                name: cs("getBlockState"),
                sig: msig([cn.block_pos.sig.to_bytes()], cn.block_state.sig.to_bytes()),
            },
            block_getter_get_tile: MSig {
                owner: cn.block_getter.clone(),
                name: cs("getBlockEntity"),
                sig: msig([cn.block_pos.sig.to_bytes()], cn.tile.sig.to_bytes()),
            },
            vec3i_x: MSig { owner: cn.vec3i.clone(), name: cs("x"), sig: cs("I") },
            vec3i_y: MSig { owner: cn.vec3i.clone(), name: cs("y"), sig: cs("I") },
            vec3i_z: MSig { owner: cn.vec3i.clone(), name: cs("z"), sig: cs("I") },
            vec3d_init: MSig { owner: cn.vec3d.clone(), name: cs("<init>"), sig: cs("(DDD)V") },
            vec3d_x: MSig { owner: cn.vec3d.clone(), name: cs("x"), sig: cs("D") },
            vec3d_y: MSig { owner: cn.vec3d.clone(), name: cs("y"), sig: cs("D") },
            vec3d_z: MSig { owner: cn.vec3d.clone(), name: cs("z"), sig: cs("D") },
            block_pos_init: MSig { owner: cn.block_pos.clone(), name: cs("<init>"), sig: cs("(III)V") },
            block_state_get_block: MSig { owner: cn.block_state.clone(), name: cs("getBlock"), sig: msig([], cn.block.sig.to_bytes()) },
            block_state_get_visual_shape: MSig {
                owner: cn.block_state.clone(),
                name: cs("getVisualShape"),
                sig: msig(
                    [cn.block_getter.sig.to_bytes(), cn.block_pos.sig.to_bytes(), cn.collision_ctx.sig.to_bytes()],
                    cn.voxel_shape.sig.to_bytes(),
                ),
            },
            blocks_fire: MSig { owner: cn.blocks.clone(), name: cs("FIRE"), sig: cn.block.sig.clone() },
            tile_supplier_create: MSig {
                owner: cn.tile_supplier.clone(),
                name: cs("create"),
                sig: msig([cn.block_pos.sig.to_bytes(), cn.block_state.sig.to_bytes()], cn.tile.sig.to_bytes()),
            },
            tile_type_init: MSig {
                owner: cn.tile_type.clone(),
                name: cs("<init>"),
                sig: msig([cn.tile_supplier.sig.to_bytes(), b"Ljava/util/Set;", cn.dfu_type.sig.to_bytes()], b"V"),
            },
            tile_init: MSig {
                owner: cn.tile.clone(),
                name: cs("<init>"),
                sig: msig([cn.tile_type.sig.to_bytes(), cn.block_pos.sig.to_bytes(), cn.block_state.sig.to_bytes()], b"V"),
            },
            tile_load_additional: MSig {
                owner: cn.tile.clone(),
                name: cs("loadAdditional"),
                sig: msig([cn.nbt_compound.sig.to_bytes(), cn.holder_provider.sig.to_bytes()], b"V"),
            },
            tile_get_update_tag: MSig {
                owner: cn.tile.clone(),
                name: cs("getUpdateTag"),
                sig: msig([cn.holder_provider.sig.to_bytes()], cn.nbt_compound.sig.to_bytes()),
            },
            tile_get_update_pkt: MSig { owner: cn.tile.clone(), name: cs("getUpdatePacket"), sig: msig([], cn.pkt.sig.to_bytes()) },
            tile_save_additional: MSig {
                owner: cn.tile.clone(),
                name: cs("saveAdditional"),
                sig: msig([cn.nbt_compound.sig.to_bytes(), cn.holder_provider.sig.to_bytes()], b"V"),
            },
            tile_level: MSig { owner: cn.tile.clone(), name: cs("level"), sig: cn.level.sig.clone() },
            tile_pos: MSig { owner: cn.tile.clone(), name: cs("worldPosition"), sig: cn.block_pos.sig.clone() },
            tile_set_removed: MSig { owner: cn.tile.clone(), name: cs("setRemoved"), sig: cs("()V") },
            tile_set_changed: MSig { owner: cn.tile.clone(), name: cs("setChanged"), sig: cs("()V") },
            sound_type_metal: MSig { owner: cn.sound_type.clone(), name: cs("METAL"), sig: cn.sound_type.sig.clone() },
            item_get_desc_id: MSig { owner: cn.item.clone(), name: cs("getDescriptionId"), sig: cs("()Ljava/lang/String;") },
            item_stack_init: MSig { owner: cn.item_stack.clone(), name: cs("<init>"), sig: msig([cn.item_like.sig.to_bytes(), b"I"], b"V") },
            creative_tab_items_gen_accept: MSig {
                owner: cn.creative_tab_items_gen.clone(),
                name: cs("accept"),
                sig: msig([cn.creative_tab_params.sig.to_bytes(), cn.creative_tab_output.sig.to_bytes()], b"V"),
            },
            render_shape_tile: MSig { owner: cn.render_shape.clone(), name: cs("ENTITYBLOCK_ANIMATED"), sig: cn.render_shape.sig.clone() },
            resource_loc_init: MSig { owner: cn.resource_loc.clone(), name: cs("<init>"), sig: cs("(Ljava/lang/String;Ljava/lang/String;)V") },
            shapes_create: MSig { owner: cn.shapes.clone(), name: cs("create"), sig: msig([B("DDDDDD")], cn.voxel_shape.sig.to_bytes()) },
            collision_ctx_empty: MSig { owner: cn.collision_ctx.clone(), name: cs("empty"), sig: msig([], cn.collision_ctx.sig.to_bytes()) },
            s2c_tile_data_create: MSig {
                owner: cn.s2c_tile_data.clone(),
                name: cs("create"),
                sig: msig([cn.tile.sig.to_bytes()], cn.s2c_tile_data.sig.to_bytes()),
            },
            nbt_compound_init: MSig { owner: cn.nbt_compound.clone(), name: cs("<init>"), sig: cs("()V") },
            nbt_compound_put_byte_array: MSig { owner: cn.nbt_compound.clone(), name: cs("putByteArray"), sig: cs("(Ljava/lang/String;[B)V") },
            nbt_compound_get_byte_array: MSig { owner: cn.nbt_compound.clone(), name: cs("getByteArray"), sig: cs("(Ljava/lang/String;)[B") },
            use_on_ctx_get_level: MSig { owner: cn.use_on_ctx.clone(), name: cs("getLevel"), sig: msig([], cn.level.sig.to_bytes()) },
            use_on_ctx_get_clicked_pos: MSig { owner: cn.use_on_ctx.clone(), name: cs("getClickedPos"), sig: msig([], cn.block_pos.sig.to_bytes()) },
            use_on_ctx_get_clicked_face: MSig { owner: cn.use_on_ctx.clone(), name: cs("getClickedFace"), sig: msig([], cn.dir.sig.to_bytes()) },
            dir_3d_data: MSig { owner: cn.dir.clone(), name: cs("data3d"), sig: cs("I") },
            dir_by_3d_data: MSig {
                owner: cn.dir.clone(),
                name: cs("BY_3D_DATA"),
                sig: cs(Vec::from_iter(b"[".iter().chain(cn.dir.sig.as_bytes()).copied())),
            },
            level_set_block_and_update: MSig {
                owner: cn.level.clone(),
                name: cs("setBlockAndUpdate"),
                sig: msig([cn.block_pos.sig.to_bytes(), cn.block_state.sig.to_bytes()], b"Z"),
            },
            level_update_neighbors_for_out_signal: MSig {
                owner: cn.level.clone(),
                name: cs("updateNeighbourForOutputSignal"),
                sig: msig([cn.block_pos.sig.to_bytes(), cn.block.sig.to_bytes()], b"V"),
            },
            level_is_client: MSig { owner: cn.level.clone(), name: cs("isClientSide"), sig: cs("Z") },
            level_get_chunk_source: MSig { owner: cn.level.clone(), name: cs("getChunkSource"), sig: msig([], cn.chunk_source.sig.to_bytes()) },
            level_is_outside_build_height: MSig { owner: cn.level.clone(), name: cs("isOutsideBuildHeight"), sig: cs("(I)Z") },
            menu_provider_create_menu: MSig {
                owner: cn.menu_provider.clone(),
                name: cs("createMenu"),
                sig: msig([b"I", cn.inventory.sig.to_bytes(), cn.player.sig.to_bytes()], cn.container_menu.sig.to_bytes()),
            },
            menu_provider_get_display_name: MSig {
                owner: cn.menu_provider.clone(),
                name: cs("getDisplayName"),
                sig: msig([], cn.chat_component.sig.to_bytes()),
            },
            chat_component_translatable: MSig {
                owner: cn.chat_component.clone(),
                name: cs("translatable"),
                sig: msig([B("Ljava/lang/String;")], cn.chat_mutable_component.sig.to_bytes()),
            },
            chat_component_literal: MSig {
                owner: cn.chat_component.clone(),
                name: cs("literal"),
                sig: msig([B("Ljava/lang/String;")], cn.chat_mutable_component.sig.to_bytes()),
            },
            chat_component_to_formatted: MSig {
                owner: cn.chat_component.clone(),
                name: cs("getVisualOrderText"),
                sig: msig([], cn.formatted_char_seq.sig.to_bytes()),
            },
            chat_fmt_from_code: MSig { owner: cn.chat_fmt.clone(), name: cs("getByCode"), sig: msig([B("C")], cn.chat_fmt.sig.to_bytes()) },
            chat_fmt_color: MSig { owner: cn.chat_fmt.clone(), name: cs("color"), sig: cs("Ljava/lang/Integer;") },
            friendly_byte_buf_read_byte_array: MSig { owner: cn.friendly_byte_buf.clone(), name: cs("readByteArray"), sig: cs("()[B") },
            friendly_byte_buf_write_byte_array: MSig {
                owner: cn.friendly_byte_buf.clone(),
                name: cs("writeByteArray"),
                sig: msig([B("[B")], cn.friendly_byte_buf.sig.to_bytes()),
            },
            inventory_player: MSig { owner: cn.inventory.clone(), name: cs("player"), sig: cn.player.sig.clone() },
            entity_level: MSig { owner: cn.entity.clone(), name: cs("level"), sig: msig([], cn.level.sig.to_bytes()) },
            entity_y_rot: MSig { owner: cn.entity.clone(), name: cs("yRot"), sig: cs("F") },
            container_still_valid: MSig {
                owner: cn.container.clone(),
                name: cs("stillValidBlockEntity"),
                sig: msig([cn.tile.sig.to_bytes(), cn.player.sig.to_bytes()], b"Z"),
            },
            player_profile: MSig { owner: cn.player.clone(), name: cs("gameProfile"), sig: cn.game_profile.sig.clone() },
            player_container_menu: MSig { owner: cn.player.clone(), name: cs("containerMenu"), sig: cn.container_menu.sig.clone() },
            game_profile_get_name: MSig { owner: cn.game_profile.clone(), name: cs("getName"), sig: cs("()Ljava/lang/String;") },
            server_chunk_cache_block_changed: MSig {
                owner: cn.server_chunk_cache.clone(),
                name: cs("blockChanged"),
                sig: msig([cn.block_pos.sig.to_bytes()], b"V"),
            },
            sound_evts_ui_btn_click: MSig { owner: cn.sound_evts.clone(), name: cs("UI_BUTTON_CLICK"), sig: cn.holder_ref.sig.clone() },
            tile_ticker_tick: MSig {
                owner: cn.tile_ticker.clone(),
                name: cs("tick"),
                sig: msig([cn.level.sig.to_bytes(), cn.block_pos.sig.to_bytes(), cn.block_state.sig.to_bytes(), cn.tile.sig.to_bytes()], b"V"),
            },
            chunk_pos_x: MSig { owner: cn.chunk_pos.clone(), name: cs("x"), sig: cs("I") },
            chunk_pos_z: MSig { owner: cn.chunk_pos.clone(), name: cs("z"), sig: cs("I") },
            voxel_shape_clip: MSig {
                owner: cn.voxel_shape.clone(),
                name: cs("clip"),
                sig: msig([cn.vec3d.sig.to_bytes(), cn.vec3d.sig.to_bytes(), cn.block_pos.sig.to_bytes()], cn.block_hit_result.sig.to_bytes()),
            },
            block_hit_result_pos: MSig { owner: cn.block_hit_result.clone(), name: cs("location"), sig: cn.vec3d.sig.clone() },
            block_hit_result_miss: MSig { owner: cn.block_hit_result.clone(), name: cs("miss"), sig: cs("Z") },
            block_hit_result_dir: MSig { owner: cn.block_hit_result.clone(), name: cs("direction"), sig: cn.dir.sig.clone() },
            chunk_access_pos: MSig { owner: cn.chunk_access.clone(), name: cs("chunkPos"), sig: cn.chunk_pos.sig.clone() },
            level_chunk_set_block_state: MSig {
                owner: cn.level_chunk.clone(),
                name: cs("setBlockState"),
                sig: msig([cn.block_pos.sig.to_bytes(), cn.block_state.sig.to_bytes(), b"Z"], cn.block_state.sig.to_bytes()),
            },
            level_chunk_level: MSig { owner: cn.level_chunk.clone(), name: cs("level"), sig: cn.level.sig.clone() },
            chunk_source_get_chunk_now: MSig {
                owner: cn.chunk_source.clone(),
                name: cs("getChunkNow"),
                sig: msig([B("II")], cn.level_chunk.sig.to_bytes()),
            },
            registry_reg: MSig {
                owner: cn.registry.clone(),
                name: cs("register"),
                sig: msig([cn.registry.sig.to_bytes(), b"Ljava/lang/String;Ljava/lang/Object;"], b"Ljava/lang/Object;"),
            },
            reg_key_block: MSig { owner: cn.registries.clone(), name: cs("BLOCK"), sig: cn.resource_key.sig.clone() },
            reg_key_tile_type: MSig { owner: cn.registries.clone(), name: cs("BLOCK_ENTITY_TYPE"), sig: cn.resource_key.sig.clone() },
            reg_key_menu: MSig { owner: cn.registries.clone(), name: cs("MENU"), sig: cn.resource_key.sig.clone() },
            custom_payload_type: MSig { owner: cn.custom_payload.clone(), name: cs("type"), sig: msig([], cn.custom_payload_type.sig.to_bytes()) },
            custom_payload_type_init: MSig {
                owner: cn.custom_payload_type.clone(),
                name: cs("<init>"),
                sig: msig([cn.resource_loc.sig.to_bytes()], b"V"),
            },
            stream_codec_encode: MSig { owner: cn.stream_codec.clone(), name: cs("encode"), sig: cs("(Ljava/lang/Object;Ljava/lang/Object;)V") },
            stream_codec_decode: MSig { owner: cn.stream_codec.clone(), name: cs("decode"), sig: cs("(Ljava/lang/Object;)Ljava/lang/Object;") },
            // Client
            tile_renderer_render: MSig {
                owner: cn.tile_renderer.clone(),
                name: cs("render"),
                sig: msig([cn.tile.sig.to_bytes(), b"F", cn.pose_stack.sig.to_bytes(), cn.multi_buffer_source.sig.to_bytes(), b"II"], b"V"),
            },
            tile_renderer_provider_create: MSig {
                owner: cn.tile_renderer_provider.clone(),
                name: cs("create"),
                sig: msig([cn.tile_renderer_provider_ctx.sig.to_bytes()], cn.tile_renderer.sig.to_bytes()),
            },
            pose_pose: MSig { owner: cn.pose.clone(), name: cs("pose"), sig: cn.matrix4f.sig.clone() },
            pose_stack_last: MSig { owner: cn.pose_stack.clone(), name: cs("last"), sig: msig([], cn.pose.sig.to_bytes()) },
            matrix4fc_read: MSig { owner: cn.matrix4fc.clone(), name: cs("getToAddress"), sig: msig([B("J")], cn.matrix4fc.sig.to_bytes()) },
            atlas_loc: MSig { owner: cn.atlas.clone(), name: cs("location"), sig: msig([], cn.resource_loc.sig.to_bytes()) },
            atlas_loc_blocks: MSig { owner: cn.atlas.clone(), name: cs("LOCATION_BLOCKS"), sig: cn.resource_loc.sig.clone() },
            atlas_get_sprite: MSig {
                owner: cn.atlas.clone(),
                name: cs("getSprite"),
                sig: msig([cn.resource_loc.sig.to_bytes()], cn.sprite.sig.to_bytes()),
            },
            sprite_u0: MSig { owner: cn.sprite.clone(), name: cs("u0"), sig: cs("F") },
            sprite_v0: MSig { owner: cn.sprite.clone(), name: cs("v0"), sig: cs("F") },
            sprite_u1: MSig { owner: cn.sprite.clone(), name: cs("u1"), sig: cs("F") },
            sprite_v1: MSig { owner: cn.sprite.clone(), name: cs("v1"), sig: cs("F") },
            sheets_solid: MSig { owner: cn.sheets.clone(), name: cs("solidBlockSheet"), sig: msig([], cn.render_type.sig.to_bytes()) },
            multi_buffer_source_get_buffer: MSig {
                owner: cn.multi_buffer_source.clone(),
                name: cs("getBuffer"),
                sig: msig([cn.render_type.sig.to_bytes()], cn.vertex_consumer.sig.to_bytes()),
            },
            buffer_source_end_batch: MSig { owner: cn.buffer_source.clone(), name: cs("endBatch"), sig: msig([cn.render_type.sig.to_bytes()], b"V") },
            vertex_consumer_vertex: MSig { owner: cn.vertex_consumer.clone(), name: cs("addVertex"), sig: cs("(FFFIFFIIFFF)V") },
            vertex_consumer_pos: MSig {
                owner: cn.vertex_consumer.clone(),
                name: cs("addVertex"),
                sig: msig([cn.matrix4f.sig.to_bytes(), b"FFF"], cn.vertex_consumer.sig.to_bytes()),
            },
            vertex_consumer_color: MSig {
                owner: cn.vertex_consumer.clone(),
                name: cs("setColor"),
                sig: msig([B("FFFF")], cn.vertex_consumer.sig.to_bytes()),
            },
            container_menu_init: MSig { owner: cn.container_menu.clone(), name: cs("<init>"), sig: msig([cn.menu_type.sig.to_bytes(), b"I"], b"V") },
            container_menu_still_valid: MSig {
                owner: cn.container_menu.clone(),
                name: cs("stillValid"),
                sig: msig([cn.player.sig.to_bytes()], b"Z"),
            },
            container_menu_quick_move_stack: MSig {
                owner: cn.container_menu.clone(),
                name: cs("quickMoveStack"),
                sig: msig([cn.player.sig.to_bytes(), b"I"], cn.item_stack.sig.to_bytes()),
            },
            container_menu_id: MSig { owner: cn.container_menu.clone(), name: cs("containerId"), sig: cs("I") },
            menu_screens_reg: MSig {
                owner: cn.menu_screens.clone(),
                name: cs("register"),
                sig: msig([cn.menu_type.sig.to_bytes(), cn.screen_constructor.sig.to_bytes()], b"V"),
            },
            screen_constructor_create: MSig {
                owner: cn.screen_constructor.clone(),
                name: cs("create"),
                sig: msig(
                    [cn.container_menu.sig.to_bytes(), cn.inventory.sig.to_bytes(), cn.chat_component.sig.to_bytes()],
                    cn.screen.sig.to_bytes(),
                ),
            },
            screen_title: MSig { owner: cn.screen.clone(), name: cs("title"), sig: cs(cn.chat_component.sig.clone()) },
            screen_font: MSig { owner: cn.screen.clone(), name: cs("font"), sig: cs(cn.font.sig.clone()) },
            screen_width: MSig { owner: cn.screen.clone(), name: cs("width"), sig: cs("I") },
            screen_height: MSig { owner: cn.screen.clone(), name: cs("height"), sig: cs("I") },
            screen_render_background: MSig {
                owner: cn.screen.clone(),
                name: cs("renderBackground"),
                sig: msig([cn.gui_graphics.sig.to_bytes(), b"IIF"], b"V"),
            },
            container_screen_init: MSig {
                owner: cn.container_screen.clone(),
                name: cs("<init>"),
                sig: msig([cn.container_menu.sig.to_bytes(), cn.inventory.sig.to_bytes(), cn.chat_component.sig.to_bytes()], b"V"),
            },
            container_screen_minit: MSig { owner: cn.container_screen.clone(), name: cs("init"), sig: cs("()V") },
            container_screen_img_width: MSig { owner: cn.container_screen.clone(), name: cs("imageWidth"), sig: cs("I") },
            container_screen_img_height: MSig { owner: cn.container_screen.clone(), name: cs("imageHeight"), sig: cs("I") },
            container_screen_title_x: MSig { owner: cn.container_screen.clone(), name: cs("titleLabelX"), sig: cs("I") },
            container_screen_title_y: MSig { owner: cn.container_screen.clone(), name: cs("titleLabelY"), sig: cs("I") },
            container_screen_left: MSig { owner: cn.container_screen.clone(), name: cs("leftPos"), sig: cs("I") },
            container_screen_top: MSig { owner: cn.container_screen.clone(), name: cs("topPos"), sig: cs("I") },
            container_screen_menu: MSig { owner: cn.container_screen.clone(), name: cs("menu"), sig: cn.container_menu.sig.clone() },
            container_screen_render_bg: MSig {
                owner: cn.container_screen.clone(),
                name: cs("renderBg"),
                sig: msig([cn.gui_graphics.sig.to_bytes(), b"FII"], b"V"),
            },
            container_screen_render_labels: MSig {
                owner: cn.container_screen.clone(),
                name: cs("renderLabels"),
                sig: msig([cn.gui_graphics.sig.to_bytes(), b"II"], b"V"),
            },
            container_screen_mouse_clicked: MSig { owner: cn.container_screen.clone(), name: cs("mouseClicked"), sig: cs("(DDI)Z") },
            container_screen_mouse_dragged: MSig { owner: cn.container_screen.clone(), name: cs("mouseDragged"), sig: cs("(DDIDD)Z") },
            container_screen_mouse_released: MSig { owner: cn.container_screen.clone(), name: cs("mouseReleased"), sig: cs("(DDI)Z") },
            gui_graphics_draw_formatted: MSig {
                owner: cn.gui_graphics.clone(),
                name: cs("drawString"),
                sig: msig([cn.font.sig.to_bytes(), cn.formatted_char_seq.sig.to_bytes(), b"IIIZ"], b"I"),
            },
            gui_graphics_pose: MSig { owner: cn.gui_graphics.clone(), name: cs("pose"), sig: cn.pose_stack.sig.clone() },
            render_sys_set_shader: MSig { owner: cn.render_sys.clone(), name: cs(b"setShader"), sig: cs("(Ljava/util/function/Supplier;)V") },
            render_sys_enable_blend: MSig { owner: cn.render_sys.clone(), name: cs(b"enableBlend"), sig: cs("()V") },
            render_sys_enable_cull: MSig { owner: cn.render_sys.clone(), name: cs(b"enableCull"), sig: cs("()V") },
            render_sys_disable_blend: MSig { owner: cn.render_sys.clone(), name: cs(b"disableBlend"), sig: cs("()V") },
            render_sys_disable_cull: MSig { owner: cn.render_sys.clone(), name: cs(b"disableCull"), sig: cs("()V") },
            game_renderer_get_pos_color_shader: MSig {
                owner: cn.game_renderer.clone(),
                name: cs(b"getPositionColorShader"),
                sig: msig([], cn.shader_inst.sig.to_bytes()),
            },
            tesselator_get_inst: MSig { owner: cn.tesselator.clone(), name: cs(b"getInstance"), sig: msig([], cn.tesselator.sig.to_bytes()) },
            tesselator_begin: MSig {
                owner: cn.tesselator.clone(),
                name: cs(b"begin"),
                sig: msig([cn.vertex_mode.sig.to_bytes(), cn.vertex_fmt.sig.to_bytes()], cn.buffer_builder.sig.to_bytes()),
            },
            vertex_mode_tris: MSig { owner: cn.vertex_mode.clone(), name: cs(b"TRIANGLES"), sig: cn.vertex_mode.sig.clone() },
            default_vertex_fmt_pos_color: MSig { owner: cn.default_vertex_fmt.clone(), name: cs(b"POSITION_COLOR"), sig: cn.vertex_fmt.sig.clone() },
            buffer_builder_build: MSig { owner: cn.buffer_builder.clone(), name: cs(b"build"), sig: msig([], cn.mesh_data.sig.to_bytes()) },
            mc_get_inst: MSig { owner: cn.mc.clone(), name: cs("getInstance"), sig: msig([], cn.mc.sig.to_bytes()) },
            mc_get_window: MSig { owner: cn.mc.clone(), name: cs("getWindow"), sig: msig([], cn.window.sig.to_bytes()) },
            mc_get_sound_mgr: MSig { owner: cn.mc.clone(), name: cs("getSoundManager"), sig: msig([], cn.sound_mgr.sig.to_bytes()) },
            mc_clear_level: MSig { owner: cn.mc.clone(), name: cs("clearClientLevel"), sig: msig([cn.screen.sig.to_bytes()], b"V") },
            mc_player: MSig { owner: cn.mc.clone(), name: cs("player"), sig: cn.local_player.sig.clone() },
            window_get_gui_scale: MSig { owner: cn.window.clone(), name: cs("getGuiScale"), sig: cs("()D") },
            font_width: MSig { owner: cn.font.clone(), name: cs("width"), sig: msig([cn.formatted_char_seq.sig.to_bytes()], b"I") },
            sound_mgr_play: MSig { owner: cn.sound_mgr.clone(), name: cs("play"), sig: msig([cn.sound_inst.sig.to_bytes()], b"V") },
            simple_sound_inst_for_ui_holder: MSig {
                owner: cn.simple_sound_inst.clone(),
                name: cs("forUI"),
                sig: msig([cn.holder.sig.to_bytes(), b"F"], cn.simple_sound_inst.sig.to_bytes()),
            },
            render_type_lightning: MSig { owner: cn.render_type.clone(), name: cs("LIGHTNING"), sig: cn.render_type.sig.clone() },
            level_renderer_buffers: MSig { owner: cn.level_renderer.clone(), name: cs("renderBuffers"), sig: cn.render_buffers.sig.clone() },
            render_buffers_buffer_source: MSig { owner: cn.render_buffers.clone(), name: cs("bufferSource"), sig: cn.buffer_source.sig.clone() },
            camera_pos: MSig { owner: cn.camera.clone(), name: cs("position"), sig: cn.vec3d.sig.clone() },
            buffer_uploader_draw: MSig {
                owner: cn.buffer_uploader.clone(),
                name: cs("drawWithShader"),
                sig: msig([cn.mesh_data.sig.to_bytes()], b"V"),
            },
            delta_tracker_get_partial_tick: MSig { owner: cn.delta_tracker.clone(), name: cs("getGameTimeDeltaPartialTick"), sig: cs("(Z)F") },
        }
    }
}

pub struct MV {
    pub base_tile_block_init: usize,
    pub block_default_state: usize,
    pub block_beh_props: GlobalRef<'static>,
    pub block_beh_props_of: usize,
    pub block_beh_props_strength: usize,
    pub block_beh_props_dyn_shape: usize,
    pub block_beh_props_sound: usize,
    pub block_item: GlobalRef<'static>,
    pub block_item_init: usize,
    pub block_item_place_block: usize,
    pub block_getter_get_block_state: usize,
    pub block_getter_get_tile: usize,
    pub vec3i_x: usize,
    pub vec3i_y: usize,
    pub vec3i_z: usize,
    pub vec3d: GlobalRef<'static>,
    pub vec3d_init: usize,
    pub vec3d_x: usize,
    pub vec3d_y: usize,
    pub vec3d_z: usize,
    pub block_pos: GlobalRef<'static>,
    pub block_pos_init: usize,
    pub block_state_get_block: usize,
    pub block_state_get_visual_shape: usize,
    pub blocks_fire: GlobalRef<'static>,
    pub tile_type: GlobalRef<'static>,
    pub tile_type_init: usize,
    pub tile: GlobalRef<'static>,
    pub tile_init: usize,
    pub tile_load_additional: usize,
    pub tile_save_additional: usize,
    pub tile_level: usize,
    pub tile_pos: usize,
    pub tile_set_removed: usize,
    pub tile_set_changed: usize,
    pub sound_type_metal: GlobalRef<'static>,
    pub item: GlobalRef<'static>,
    pub item_get_desc_id: usize,
    pub item_stack: GlobalRef<'static>,
    pub item_stack_init: usize,
    pub render_shape_tile: GlobalRef<'static>,
    pub resource_loc: GlobalRef<'static>,
    pub resource_loc_init: usize,
    pub shapes: GlobalRef<'static>,
    pub shapes_create: usize,
    pub nbt_compound: GlobalRef<'static>,
    pub nbt_compound_init: usize,
    pub nbt_compound_put_byte_array: usize,
    pub nbt_compound_get_byte_array: usize,
    pub use_on_ctx_get_level: usize,
    pub use_on_ctx_get_clicked_pos: usize,
    pub use_on_ctx_get_clicked_face: usize,
    pub dir_3d_data: usize,
    pub dir_by_3d_data: GlobalRef<'static>,
    pub level_set_block_and_update: usize,
    pub level_update_neighbors_for_out_signal: usize,
    pub level_is_client: usize,
    pub level_get_chunk_source: usize,
    pub level_is_outside_build_height: usize,
    pub friendly_byte_buf_read_byte_array: usize,
    pub friendly_byte_buf_write_byte_array: usize,
    pub container_menu_init: usize,
    pub container_menu_id: usize,
    pub chat_component: GlobalRef<'static>,
    pub chat_component_translatable: usize,
    pub chat_component_literal: usize,
    pub chat_component_to_formatted: usize,
    pub chat_fmt: GlobalRef<'static>,
    pub chat_fmt_from_code: usize,
    pub chat_fmt_color: usize,
    pub interaction_result_pass: GlobalRef<'static>,
    pub interaction_result_success: GlobalRef<'static>,
    pub interaction_result_consume: GlobalRef<'static>,
    pub server_player: GlobalRef<'static>,
    pub inventory_player: usize,
    pub entity_level: usize,
    pub entity_y_rot: usize,
    pub container: GlobalRef<'static>,
    pub container_still_valid: usize,
    pub player_profile: usize,
    pub player_container_menu: usize,
    pub game_profile_get_name: usize,
    pub sound_evts_ui_btn_click: GlobalRef<'static>,
    pub server_chunk_cache_block_changed: usize,
    pub chunk_pos_x: usize,
    pub chunk_pos_z: usize,
    pub collision_ctx_empty: GlobalRef<'static>,
    pub voxel_shape_clip: usize,
    pub block_hit_result_pos: usize,
    pub block_hit_result_miss: usize,
    pub block_hit_result_dir: usize,
    pub chunk_access_pos: usize,
    pub level_chunk: GlobalRef<'static>,
    pub chunk_source_get_chunk_now: usize,
    pub registry: GlobalRef<'static>,
    pub registry_reg: usize,
    pub reg_key_block: GlobalRef<'static>,
    pub reg_key_tile_type: GlobalRef<'static>,
    pub reg_key_menu: GlobalRef<'static>,
    pub custom_payload_type: GlobalRef<'static>,
    pub custom_payload_type_init: usize,
    pub client: Option<MVC>,
}

pub struct MVC {
    pub pose_pose: usize,
    pub pose_stack_last: usize,
    pub matrix4fc_read: usize,
    pub atlas_loc: usize,
    pub atlas_loc_blocks: GlobalRef<'static>,
    pub atlas_get_sprite: usize,
    pub sprite_u0: usize,
    pub sprite_v0: usize,
    pub sprite_u1: usize,
    pub sprite_v1: usize,
    pub multi_buffer_source_get_buffer: usize,
    pub buffer_source_end_batch: usize,
    pub vertex_consumer_vertex: usize,
    pub vertex_consumer_pos: usize,
    pub vertex_consumer_color: usize,
    pub menu_screens: GlobalRef<'static>,
    pub menu_screens_reg: usize,
    pub screen_title: usize,
    pub screen_font: usize,
    pub screen_width: usize,
    pub screen_height: usize,
    pub screen_render_background: usize,
    pub container_screen: GlobalRef<'static>,
    pub container_screen_init: usize,
    pub container_screen_img_width: usize,
    pub container_screen_img_height: usize,
    pub container_screen_title_x: usize,
    pub container_screen_title_y: usize,
    pub container_screen_left: usize,
    pub container_screen_top: usize,
    pub container_screen_menu: usize,
    pub container_screen_mouse_clicked: usize,
    pub container_screen_mouse_dragged: usize,
    pub container_screen_mouse_released: usize,
    pub gui_graphics_draw_formatted: usize,
    pub gui_graphics_pose: usize,
    pub render_sys: GlobalRef<'static>,
    pub render_sys_set_shader: usize,
    pub render_sys_enable_blend: usize,
    pub render_sys_enable_cull: usize,
    pub render_sys_disable_blend: usize,
    pub render_sys_disable_cull: usize,
    pub tesselator: GlobalRef<'static>,
    pub tesselator_get_inst: usize,
    pub tesselator_begin: usize,
    pub vertex_mode_tris: GlobalRef<'static>,
    pub default_vertex_fmt_pos_color: GlobalRef<'static>,
    pub buffer_builder_build: usize,
    pub game_renderer: GlobalRef<'static>,
    pub game_renderer_get_pos_color_shader: usize,
    pub window_inst: GlobalRef<'static>,
    pub window_get_gui_scale: usize,
    pub font_width: usize,
    pub mc: GlobalRef<'static>,
    pub mc_inst: GlobalRef<'static>,
    pub mc_get_sound_mgr: usize,
    pub mc_player: usize,
    pub sound_mgr_play: usize,
    pub simple_sound_inst: GlobalRef<'static>,
    pub simple_sound_inst_for_ui_holder: usize,
    pub render_type_lightning: GlobalRef<'static>,
    pub level_renderer_buffers: usize,
    pub render_buffers_buffer_source: usize,
    pub camera_pos: usize,
    pub buffer_uploader: GlobalRef<'static>,
    pub buffer_uploader_draw: usize,
    pub delta_tracker_get_partial_tick: usize,
}

impl MV {
    pub fn new(av: &AV<'static>, cn: &CN<Arc<CSig>>, mn: &MN<MSig>, is_client: bool) -> MV {
        let load = |csig: &Arc<CSig>| av.ldr.load_class(&av.jv, &csig.dot).unwrap().new_global_ref().unwrap();
        let base_tile_block = load(&cn.base_tile_block);
        let block = load(&cn.block);
        let block_beh_props = load(&cn.block_beh_props);
        let block_item = load(&cn.block_item);
        let block_getter = load(&cn.block_getter);
        let vec3i = load(&cn.vec3i);
        let vec3d = load(&cn.vec3d);
        let block_pos = load(&cn.block_pos);
        let block_state = load(&cn.block_state);
        let tile_type = load(&cn.tile_type);
        let tile = load(&cn.tile);
        let sound_type = load(&cn.sound_type);
        let item = load(&cn.item);
        let item_stack = load(&cn.item_stack);
        let render_shape = load(&cn.render_shape);
        let resource_loc = load(&cn.resource_loc);
        let shapes = load(&cn.shapes);
        let nbt_compound = load(&cn.nbt_compound);
        let use_on_ctx = load(&cn.use_on_ctx);
        let dir = load(&cn.dir);
        let level = load(&cn.level);
        let friendly_byte_buf = load(&cn.friendly_byte_buf);
        let container_menu = load(&cn.container_menu);
        let chat_component = load(&cn.chat_component);
        let chat_fmt = load(&cn.chat_fmt);
        let interaction_result = load(&cn.interaction_result);
        let container = load(&cn.container);
        let player = load(&cn.player);
        let chunk_pos = load(&cn.chunk_pos);
        let server_player = load(&cn.server_player);
        let collision_ctx = load(&cn.collision_ctx);
        let collision_ctx_empty = mn.collision_ctx_empty.get_static_method_id(&collision_ctx).unwrap();
        let block_hit_result = load(&cn.block_hit_result);
        let registry = load(&cn.registry);
        let registries = load(&cn.registries);
        let custom_payload_type = load(&cn.custom_payload_type);
        MV {
            base_tile_block_init: mn.base_tile_block_init.get_method_id(&base_tile_block).unwrap(),
            block_default_state: mn.block_default_state.get_method_id(&block).unwrap(),
            block_beh_props_of: mn.block_beh_props_of.get_static_method_id(&block_beh_props).unwrap(),
            block_beh_props_strength: mn.block_beh_props_strength.get_method_id(&block_beh_props).unwrap(),
            block_beh_props_dyn_shape: mn.block_beh_props_dyn_shape.get_method_id(&block_beh_props).unwrap(),
            block_beh_props_sound: mn.block_beh_props_sound.get_method_id(&block_beh_props).unwrap(),
            block_beh_props,
            block_item_init: mn.block_item_init.get_method_id(&block_item).unwrap(),
            block_item_place_block: mn.block_item_place_block.get_method_id(&block_item).unwrap(),
            block_item,
            block_getter_get_block_state: mn.block_getter_get_block_state.get_method_id(&block_getter).unwrap(),
            block_getter_get_tile: mn.block_getter_get_tile.get_method_id(&block_getter).unwrap(),
            vec3i_x: mn.vec3i_x.get_field_id(&vec3i).unwrap(),
            vec3i_y: mn.vec3i_y.get_field_id(&vec3i).unwrap(),
            vec3i_z: mn.vec3i_z.get_field_id(&vec3i).unwrap(),
            vec3d_init: mn.vec3d_init.get_method_id(&vec3d).unwrap(),
            vec3d_x: mn.vec3d_x.get_field_id(&vec3d).unwrap(),
            vec3d_y: mn.vec3d_y.get_field_id(&vec3d).unwrap(),
            vec3d_z: mn.vec3d_z.get_field_id(&vec3d).unwrap(),
            vec3d,
            block_pos_init: mn.block_pos_init.get_method_id(&block_pos).unwrap(),
            block_pos,
            block_state_get_block: mn.block_state_get_block.get_method_id(&block_state).unwrap(),
            block_state_get_visual_shape: mn.block_state_get_visual_shape.get_method_id(&block_state).unwrap(),
            blocks_fire: load(&cn.blocks).static_field_2(&mn.blocks_fire),
            tile_type_init: mn.tile_type_init.get_method_id(&tile_type).unwrap(),
            tile_type,
            tile_init: mn.tile_init.get_method_id(&tile).unwrap(),
            tile_load_additional: mn.tile_load_additional.get_method_id(&tile).unwrap(),
            tile_save_additional: mn.tile_save_additional.get_method_id(&tile).unwrap(),
            tile_level: mn.tile_level.get_field_id(&tile).unwrap(),
            tile_pos: mn.tile_pos.get_field_id(&tile).unwrap(),
            tile_set_removed: mn.tile_set_removed.get_method_id(&tile).unwrap(),
            tile_set_changed: mn.tile_set_changed.get_method_id(&tile).unwrap(),
            tile,
            sound_type_metal: sound_type.static_field_2(&mn.sound_type_metal),
            item_get_desc_id: mn.item_get_desc_id.get_method_id(&item).unwrap(),
            item,
            item_stack_init: mn.item_stack_init.get_method_id(&item_stack).unwrap(),
            item_stack,
            render_shape_tile: render_shape.static_field_2(&mn.render_shape_tile),
            resource_loc_init: mn.resource_loc_init.get_method_id(&resource_loc).unwrap(),
            resource_loc,
            shapes_create: mn.shapes_create.get_static_method_id(&shapes).unwrap(),
            shapes,
            nbt_compound_init: mn.nbt_compound_init.get_method_id(&nbt_compound).unwrap(),
            nbt_compound_put_byte_array: mn.nbt_compound_put_byte_array.get_method_id(&nbt_compound).unwrap(),
            nbt_compound_get_byte_array: mn.nbt_compound_get_byte_array.get_method_id(&nbt_compound).unwrap(),
            nbt_compound,
            use_on_ctx_get_level: mn.use_on_ctx_get_level.get_method_id(&use_on_ctx).unwrap(),
            use_on_ctx_get_clicked_pos: mn.use_on_ctx_get_clicked_pos.get_method_id(&use_on_ctx).unwrap(),
            use_on_ctx_get_clicked_face: mn.use_on_ctx_get_clicked_face.get_method_id(&use_on_ctx).unwrap(),
            dir_3d_data: mn.dir_3d_data.get_field_id(&dir).unwrap(),
            dir_by_3d_data: dir.static_field_2(&mn.dir_by_3d_data),
            level_set_block_and_update: mn.level_set_block_and_update.get_method_id(&level).unwrap(),
            level_update_neighbors_for_out_signal: mn.level_update_neighbors_for_out_signal.get_method_id(&level).unwrap(),
            level_is_client: mn.level_is_client.get_field_id(&level).unwrap(),
            level_get_chunk_source: mn.level_get_chunk_source.get_method_id(&level).unwrap(),
            level_is_outside_build_height: mn.level_is_outside_build_height.get_method_id(&level).unwrap(),
            friendly_byte_buf_read_byte_array: mn.friendly_byte_buf_read_byte_array.get_method_id(&friendly_byte_buf).unwrap(),
            friendly_byte_buf_write_byte_array: mn.friendly_byte_buf_write_byte_array.get_method_id(&friendly_byte_buf).unwrap(),
            container_menu_init: mn.container_menu_init.get_method_id(&container_menu).unwrap(),
            container_menu_id: mn.container_menu_id.get_field_id(&container_menu).unwrap(),
            chat_component_translatable: mn.chat_component_translatable.get_static_method_id(&chat_component).unwrap(),
            chat_component_literal: mn.chat_component_literal.get_static_method_id(&chat_component).unwrap(),
            chat_component_to_formatted: mn.chat_component_to_formatted.get_method_id(&chat_component).unwrap(),
            chat_component,
            chat_fmt_from_code: mn.chat_fmt_from_code.get_static_method_id(&chat_fmt).unwrap(),
            chat_fmt_color: mn.chat_fmt_color.get_field_id(&chat_fmt).unwrap(),
            chat_fmt,
            interaction_result_pass: interaction_result.static_field_1(c"PASS", &cn.interaction_result.sig),
            interaction_result_success: interaction_result.static_field_1(c"SUCCESS", &cn.interaction_result.sig),
            interaction_result_consume: interaction_result.static_field_1(c"CONSUME", &cn.interaction_result.sig),
            server_player,
            inventory_player: mn.inventory_player.get_field_id(&load(&cn.inventory)).unwrap(),
            entity_level: mn.entity_level.get_method_id(&load(&cn.entity)).unwrap(),
            entity_y_rot: mn.entity_y_rot.get_field_id(&load(&cn.entity)).unwrap(),
            container_still_valid: mn.container_still_valid.get_static_method_id(&container).unwrap(),
            container,
            player_profile: mn.player_profile.get_field_id(&player).unwrap(),
            player_container_menu: mn.player_container_menu.get_field_id(&player).unwrap(),
            game_profile_get_name: mn.game_profile_get_name.get_method_id(&load(&cn.game_profile)).unwrap(),
            sound_evts_ui_btn_click: load(&cn.sound_evts).static_field_2(&mn.sound_evts_ui_btn_click),
            server_chunk_cache_block_changed: mn.server_chunk_cache_block_changed.get_method_id(&load(&cn.server_chunk_cache)).unwrap(),
            chunk_pos_x: mn.chunk_pos_x.get_field_id(&chunk_pos).unwrap(),
            chunk_pos_z: mn.chunk_pos_z.get_field_id(&chunk_pos).unwrap(),
            collision_ctx_empty: collision_ctx.call_static_object_method(collision_ctx_empty, &[]).unwrap().unwrap().new_global_ref().unwrap(),
            voxel_shape_clip: mn.voxel_shape_clip.get_method_id(&load(&cn.voxel_shape)).unwrap(),
            block_hit_result_pos: mn.block_hit_result_pos.get_field_id(&block_hit_result).unwrap(),
            block_hit_result_miss: mn.block_hit_result_miss.get_field_id(&block_hit_result).unwrap(),
            block_hit_result_dir: mn.block_hit_result_dir.get_field_id(&block_hit_result).unwrap(),
            chunk_access_pos: mn.chunk_access_pos.get_field_id(&load(&cn.chunk_access)).unwrap(),
            level_chunk: load(&cn.level_chunk),
            chunk_source_get_chunk_now: mn.chunk_source_get_chunk_now.get_method_id(&load(&cn.chunk_source)).unwrap(),
            registry_reg: mn.registry_reg.get_static_method_id(&registry).unwrap(),
            registry,
            reg_key_block: registries.static_field_2(&mn.reg_key_block),
            reg_key_tile_type: registries.static_field_2(&mn.reg_key_tile_type),
            reg_key_menu: registries.static_field_2(&mn.reg_key_menu),
            custom_payload_type_init: mn.custom_payload_type_init.get_method_id(&custom_payload_type).unwrap(),
            custom_payload_type,
            client: is_client.then(|| {
                let pose = load(&cn.pose);
                let pose_stack = load(&cn.pose_stack);
                let matrix4fc = load(&cn.matrix4fc);
                let atlas = load(&cn.atlas);
                let sprite = load(&cn.sprite);
                let vertex_consumer = load(&cn.vertex_consumer);
                let menu_screens = load(&cn.menu_screens);
                let screen = load(&cn.screen);
                let container_screen = load(&cn.container_screen);
                let gui_graphics = load(&cn.gui_graphics);
                let render_sys = load(&cn.render_sys);
                let tesselator = load(&cn.tesselator);
                let buffer_builder = load(&cn.buffer_builder);
                let vertex_mode = load(&cn.vertex_mode);
                let default_vertex_fmt = load(&cn.default_vertex_fmt);
                let game_renderer = load(&cn.game_renderer);
                let mc = load(&cn.mc);
                let mc_inst = mc.call_static_object_method(mn.mc_get_inst.get_static_method_id(&mc).unwrap(), &[]).unwrap().unwrap();
                let window_inst = mc_inst.call_object_method(mn.mc_get_window.get_method_id(&mc).unwrap(), &[]).unwrap().unwrap();
                let window = window_inst.get_object_class();
                let simple_sound_inst = load(&cn.simple_sound_inst);
                let buffer_uploader = load(&cn.buffer_uploader);
                MVC {
                    pose_pose: mn.pose_pose.get_field_id(&pose).unwrap(),
                    pose_stack_last: mn.pose_stack_last.get_method_id(&pose_stack).unwrap(),
                    matrix4fc_read: mn.matrix4fc_read.get_method_id(&matrix4fc).unwrap(),
                    atlas_loc: mn.atlas_loc.get_method_id(&atlas).unwrap(),
                    atlas_loc_blocks: atlas.static_field_2(&mn.atlas_loc_blocks),
                    atlas_get_sprite: mn.atlas_get_sprite.get_method_id(&atlas).unwrap(),
                    sprite_u0: mn.sprite_u0.get_field_id(&sprite).unwrap(),
                    sprite_v0: mn.sprite_v0.get_field_id(&sprite).unwrap(),
                    sprite_u1: mn.sprite_u1.get_field_id(&sprite).unwrap(),
                    sprite_v1: mn.sprite_v1.get_field_id(&sprite).unwrap(),
                    multi_buffer_source_get_buffer: mn.multi_buffer_source_get_buffer.get_method_id(&load(&cn.multi_buffer_source)).unwrap(),
                    buffer_source_end_batch: mn.buffer_source_end_batch.get_method_id(&load(&cn.buffer_source)).unwrap(),
                    vertex_consumer_vertex: mn.vertex_consumer_vertex.get_method_id(&vertex_consumer).unwrap(),
                    vertex_consumer_pos: mn.vertex_consumer_pos.get_method_id(&vertex_consumer).unwrap(),
                    vertex_consumer_color: mn.vertex_consumer_color.get_method_id(&vertex_consumer).unwrap(),
                    menu_screens_reg: mn.menu_screens_reg.get_static_method_id(&menu_screens).unwrap(),
                    menu_screens,
                    screen_title: mn.screen_title.get_field_id(&screen).unwrap(),
                    screen_font: mn.screen_font.get_field_id(&screen).unwrap(),
                    screen_width: mn.screen_width.get_field_id(&screen).unwrap(),
                    screen_height: mn.screen_height.get_field_id(&screen).unwrap(),
                    screen_render_background: mn.screen_render_background.get_method_id(&screen).unwrap(),
                    container_screen_init: mn.container_screen_init.get_method_id(&container_screen).unwrap(),
                    container_screen_img_width: mn.container_screen_img_width.get_field_id(&container_screen).unwrap(),
                    container_screen_img_height: mn.container_screen_img_height.get_field_id(&container_screen).unwrap(),
                    container_screen_title_x: mn.container_screen_title_x.get_field_id(&container_screen).unwrap(),
                    container_screen_title_y: mn.container_screen_title_y.get_field_id(&container_screen).unwrap(),
                    container_screen_left: mn.container_screen_left.get_field_id(&container_screen).unwrap(),
                    container_screen_top: mn.container_screen_top.get_field_id(&container_screen).unwrap(),
                    container_screen_menu: mn.container_screen_menu.get_field_id(&container_screen).unwrap(),
                    container_screen_mouse_clicked: mn.container_screen_mouse_clicked.get_method_id(&container_screen).unwrap(),
                    container_screen_mouse_dragged: mn.container_screen_mouse_dragged.get_method_id(&container_screen).unwrap(),
                    container_screen_mouse_released: mn.container_screen_mouse_released.get_method_id(&container_screen).unwrap(),
                    container_screen,
                    gui_graphics_draw_formatted: mn.gui_graphics_draw_formatted.get_method_id(&gui_graphics).unwrap(),
                    gui_graphics_pose: mn.gui_graphics_pose.get_field_id(&gui_graphics).unwrap(),
                    render_sys_set_shader: mn.render_sys_set_shader.get_static_method_id(&render_sys).unwrap(),
                    render_sys_enable_blend: mn.render_sys_enable_blend.get_static_method_id(&render_sys).unwrap(),
                    render_sys_enable_cull: mn.render_sys_enable_cull.get_static_method_id(&render_sys).unwrap(),
                    render_sys_disable_blend: mn.render_sys_disable_blend.get_static_method_id(&render_sys).unwrap(),
                    render_sys_disable_cull: mn.render_sys_disable_cull.get_static_method_id(&render_sys).unwrap(),
                    render_sys,
                    tesselator_get_inst: mn.tesselator_get_inst.get_static_method_id(&tesselator).unwrap(),
                    tesselator_begin: mn.tesselator_begin.get_method_id(&tesselator).unwrap(),
                    tesselator,
                    vertex_mode_tris: vertex_mode.static_field_2(&mn.vertex_mode_tris),
                    default_vertex_fmt_pos_color: default_vertex_fmt.static_field_2(&mn.default_vertex_fmt_pos_color),
                    buffer_builder_build: mn.buffer_builder_build.get_method_id(&buffer_builder).unwrap(),
                    game_renderer_get_pos_color_shader: mn.game_renderer_get_pos_color_shader.get_static_method_id(&game_renderer).unwrap(),
                    game_renderer,
                    window_get_gui_scale: mn.window_get_gui_scale.get_method_id(&window).unwrap(),
                    window_inst: window_inst.new_global_ref().unwrap(),
                    font_width: mn.font_width.get_method_id(&load(&cn.font)).unwrap(),
                    mc_get_sound_mgr: mn.mc_get_sound_mgr.get_method_id(&mc).unwrap(),
                    mc_player: mn.mc_player.get_field_id(&mc).unwrap(),
                    mc_inst: mc_inst.new_global_ref().unwrap(),
                    mc,
                    sound_mgr_play: mn.sound_mgr_play.get_method_id(&load(&cn.sound_mgr)).unwrap(),
                    simple_sound_inst_for_ui_holder: mn.simple_sound_inst_for_ui_holder.get_static_method_id(&simple_sound_inst).unwrap(),
                    simple_sound_inst,
                    render_type_lightning: load(&cn.render_type).static_field_2(&mn.render_type_lightning),
                    level_renderer_buffers: mn.level_renderer_buffers.get_field_id(&load(&cn.level_renderer)).unwrap(),
                    render_buffers_buffer_source: mn.render_buffers_buffer_source.get_field_id(&load(&cn.render_buffers)).unwrap(),
                    camera_pos: mn.camera_pos.get_field_id(&load(&cn.camera)).unwrap(),
                    buffer_uploader_draw: mn.buffer_uploader_draw.get_static_method_id(&buffer_uploader).unwrap(),
                    buffer_uploader,
                    delta_tracker_get_partial_tick: mn.delta_tracker_get_partial_tick.get_method_id(&load(&cn.delta_tracker)).unwrap(),
                }
            }),
        }
    }
}

#[derive(Functor)]
pub struct GregCN<T> {
    pub reg: T,
    pub item_builder: T,
    pub non_null_fn: T,
    pub creative_tab_items_gen: T,
    pub values: T,
    pub caps: T,
    pub dyn_resource_pack: T,
    pub material_block_renderer: T,
    pub energy_container: T,
    pub pipe_block: T,
    pub pipe_node: T,
}

impl GregCN<Arc<CSig>> {
    pub fn new() -> Self {
        let names = GregCN::<&[u8]> {
            reg: b"com.gregtechceu.gtceu.api.registry.registrate.GTRegistrate",
            item_builder: b"com.tterrag.registrate.builders.ItemBuilder",
            non_null_fn: b"com.tterrag.registrate.util.nullness.NonNullFunction",
            creative_tab_items_gen: b"com.gregtechceu.gtceu.data.GTCreativeModeTabs$RegistrateDisplayItemsGenerator",
            values: b"com.gregtechceu.gtceu.api.GTValues",
            caps: b"com.gregtechceu.gtceu.api.capability.GTCapability",
            dyn_resource_pack: b"com.gregtechceu.gtceu.data.pack.GTDynamicResourcePack",
            material_block_renderer: b"com.gregtechceu.gtceu.client.renderer.block.MaterialBlockRenderer",
            energy_container: b"com.gregtechceu.gtceu.api.capability.IEnergyContainer",
            pipe_block: b"com.gregtechceu.gtceu.api.block.PipeBlock",
            pipe_node: b"com.gregtechceu.gtceu.api.pipenet.IPipeNode",
        };
        names.fmap(|x| Arc::new(CSig::new(x)))
    }
}

pub struct GregMN {
    pub reg_item: MSig,
    pub can_input_eu_from_side: MSig,
    pub accept_eu: MSig,
    pub change_eu: MSig,
    pub get_eu_stored: MSig,
    pub get_eu_capacity: MSig,
    pub get_input_amps: MSig,
    pub get_input_volts: MSig,
    pub get_input_eu_per_sec: MSig,
    pub pipe_block_get_node: MSig,
    pub pipe_block_can_connect: MSig,
    pub pipe_node_set_conn: MSig,
}

impl GregMN {
    pub fn new(cn: &CN<Arc<CSig>>, gcn: &GregCN<Arc<CSig>>) -> Self {
        GregMN {
            reg_item: MSig {
                owner: gcn.reg.clone(),
                name: cs("item"),
                sig: msig([b"Ljava/lang/String;", gcn.non_null_fn.sig.to_bytes()], gcn.item_builder.sig.to_bytes()),
            },
            can_input_eu_from_side: MSig { owner: gcn.energy_container.clone(), name: cs("inputsEnergy"), sig: msig([cn.dir.sig.to_bytes()], b"Z") },
            accept_eu: MSig {
                owner: gcn.energy_container.clone(),
                name: cs("acceptEnergyFromNetwork"),
                sig: msig([cn.dir.sig.to_bytes(), b"JJ"], b"J"),
            },
            change_eu: MSig { owner: gcn.energy_container.clone(), name: cs("changeEnergy"), sig: cs("(J)J") },
            get_eu_stored: MSig { owner: gcn.energy_container.clone(), name: cs("getEnergyStored"), sig: cs("()J") },
            get_eu_capacity: MSig { owner: gcn.energy_container.clone(), name: cs("getEnergyCapacity"), sig: cs("()J") },
            get_input_amps: MSig { owner: gcn.energy_container.clone(), name: cs("getInputAmperage"), sig: cs("()J") },
            get_input_volts: MSig { owner: gcn.energy_container.clone(), name: cs("getInputVoltage"), sig: cs("()J") },
            get_input_eu_per_sec: MSig { owner: gcn.energy_container.clone(), name: cs("getInputPerSec"), sig: cs("()J") },
            pipe_block_get_node: MSig {
                owner: gcn.pipe_block.clone(),
                name: cs("getPipeTile"),
                sig: msig([cn.block_getter.sig.to_bytes(), cn.block_pos.sig.to_bytes()], gcn.pipe_node.sig.to_bytes()),
            },
            pipe_block_can_connect: MSig {
                owner: gcn.pipe_block.clone(),
                name: cs("canPipeConnectToBlock"),
                sig: msig([gcn.pipe_node.sig.to_bytes(), cn.dir.sig.to_bytes(), cn.tile.sig.to_bytes()], b"Z"),
            },
            pipe_node_set_conn: MSig { owner: gcn.pipe_node.clone(), name: cs("setConnection"), sig: msig([cn.dir.sig.to_bytes(), b"ZZ"], b"V") },
        }
    }
}

pub struct GregMV {
    pub tier_names: GlobalRef<'static>,
    pub tier_volts: GlobalRef<'static>,
    pub tier_fmt_names: GlobalRef<'static>,
    pub dyn_resource_pack_data: GlobalRef<'static>,
    pub energy_container_cap: GlobalRef<'static>,
    pub pipe_block: GlobalRef<'static>,
    pub pipe_block_get_node: usize,
    pub pipe_block_can_connect: usize,
    pub pipe_node_set_conn: usize,
    pub can_input_eu_from_side: usize,
    pub accept_eu: usize,
}

impl GregMV {
    pub fn new(jni: &'static JNI) -> Self {
        let GlobalObjs { av, fcn, gcn, gmn, .. } = objs();
        let load = |csig: &Arc<CSig>| av.ldr.with_jni(jni).load_class(&av.jv, &csig.dot).unwrap().new_global_ref().unwrap();
        let values = load(&gcn.values);
        let pipe_block = load(&gcn.pipe_block);
        let energy_container = load(&gcn.energy_container);
        Self {
            tier_names: values.static_field_1(c"VN", c"[Ljava/lang/String;"),
            tier_volts: values.static_field_1(c"V", c"[J"),
            tier_fmt_names: values.static_field_1(c"VNF", c"[Ljava/lang/String;"),
            dyn_resource_pack_data: load(&gcn.dyn_resource_pack).static_field_1(c"DATA", c"Ljava/util/concurrent/ConcurrentMap;"),
            energy_container_cap: load(&gcn.caps).static_field_1(c"CAPABILITY_ENERGY_CONTAINER", &fcn.block_cap.sig),
            pipe_block_get_node: gmn.pipe_block_get_node.get_method_id(&pipe_block).unwrap(),
            pipe_block_can_connect: gmn.pipe_block_can_connect.get_method_id(&pipe_block).unwrap(),
            pipe_block,
            pipe_node_set_conn: gmn.pipe_node_set_conn.get_method_id(&load(&gcn.pipe_node)).unwrap(),
            can_input_eu_from_side: gmn.can_input_eu_from_side.get_method_id(&energy_container).unwrap(),
            accept_eu: gmn.accept_eu.get_method_id(&energy_container).unwrap(),
        }
    }
}
